apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: pv0088
  name: pv0088
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /tmp/pv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - localhost
