kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
  annotations:
   volume.beta.kubernetes.io/storage-class: nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
